export const chains = {
  cosmos: {
    chainID: 'cosmoshub-3',
    networkNameLC: 'cosmos',
    networkNameUC: 'COSMOS',
    networkNameProper: 'Cosmos',
    tokenDenom: 'atom',
    delegationDenom: 'uatom',
    denomMultiplier: 1000000,
    fee: 100,
    gas: 175000,
  },
  iris: {
    chainID: 'irishub',
    networkNameLC: 'iris',
    networkNameUC: 'IRIS',
    networkNameProper: 'Iris',
    tokenDenom: 'iris',
    delegationDenom: 'iris-atto',
    denomMultiplier: 10000000000000000000,
    fee: 500000000000000000,
    gas: 50000,
  },
  kava: {
    chainID: 'kava-2',
    networkNameLC: 'kava',
    networkNameUC: 'KAVA',
    networkNameProper: 'Kava',
    tokenDenom: 'kava',
    delegationDenom: 'ukava',
    denomMultiplier: 1000000,
    fee: 100,
    gas: 175000,
  },
  terra: {
    chainID: 'columbus-3',
    networkNameLC: 'terra',
    networkNameUC: 'TERRA',
    networkNameProper: 'Terra',
    tokenDenom: 'luna',
    delegationDenom: 'kluna',
    denomMultiplier: 1000000,
    fee: 100,
    gas: 175000,
  },
};
